baseURL = 'https://lishuangquan1987.github.io/'
languageCode = 'en-us'
title = 'Tony Blog'
theme = 'm10c'
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Tony"
  description = "familiar with c#,go,lua,vb6"
  menu_item_separator = "  Â·  "
  [[params.social]]
    icon = "circle"
    name = "CSDN"
    url = "https://blog.csdn.net/lishuangquan1987"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/lishuangquan1987"
  

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
